theme: alembic-jekyll-theme
markdown: kramdown

plugins:
- jekyll-feed

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [vendor, README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
